// <auto-generated />
using System;
using EnglishLearning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnglishLearning.Migrations
{
    [DbContext(typeof(EnglishLearningDbContext))]
    [Migration("20181012051228_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnglishLearningDomain.Entities.Administrator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("created_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnName("created_date_time_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnName("normalized_email")
                        .HasMaxLength(100);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnName("updated_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("UpdatedDateTimeUtc")
                        .HasColumnName("updated_date_time_utc");

                    b.HasKey("Id")
                        .HasName("pk_administrators");

                    b.ToTable("administrators");
                });

            modelBuilder.Entity("EnglishLearningDomain.Entities.RelatedWords", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("ChineseMeaning")
                        .HasColumnName("chinese_meaning")
                        .HasMaxLength(300);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("created_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnName("created_date_time_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<bool>("RememberLogic")
                        .HasColumnName("remember_logic")
                        .HasMaxLength(400);

                    b.Property<long>("RootId")
                        .HasColumnName("root_id");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnName("updated_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("UpdatedDateTimeUtc")
                        .HasColumnName("updated_date_time_utc");

                    b.Property<bool>("Word")
                        .HasColumnName("word")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_related_words");

                    b.ToTable("related_words");
                });

            modelBuilder.Entity("EnglishLearningDomain.Entities.WordRoots", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("ChineseMeaning")
                        .HasColumnName("chinese_meaning")
                        .HasMaxLength(300);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("created_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnName("created_date_time_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnName("updated_by")
                        .HasMaxLength(64);

                    b.Property<DateTime>("UpdatedDateTimeUtc")
                        .HasColumnName("updated_date_time_utc");

                    b.Property<bool>("Word")
                        .HasColumnName("word")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_word_roots");

                    b.ToTable("word_roots");
                });
#pragma warning restore 612, 618
        }
    }
}
